-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 16:58:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Volo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Volo` (
  `codice_volo` VARCHAR(8) NOT NULL,
  `aereo` VARCHAR(45) NOT NULL,
  `città_partenza` VARCHAR(45) NOT NULL,
  `città_arrivo` VARCHAR(45) NOT NULL,
  `data_partenza` DATE NOT NULL,
  `data_arrivo` DATE NOT NULL,
  `ora_partenza` TIME NOT NULL,
  `ora_arrivo` TIME NOT NULL,
  `KmTratta` DECIMAL(2) NOT NULL,
  `prezzo` DECIMAL(2) NOT NULL,
  `puntiOttenuti` INT NOT NULL,
  PRIMARY KEY (`codice_volo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utente` (
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `dataNascita` VARCHAR(45) NULL,
  `ultimoAcquisto` DATE NULL,
  `indirizzoCasa` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `infedele` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prenotazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prenotazione` (
  `codicePrenotazione` INT NOT NULL,
  `dataScadenza` DATE NOT NULL,
  `dataPrenotazione` DATE NOT NULL,
  `penaleModifica` DECIMAL(2) NULL,
  `utente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codicePrenotazione`),
  INDEX `utente_idx` (`utente` ASC) VISIBLE,
  CONSTRAINT `utentePrenotazione`
    FOREIGN KEY (`utente`)
    REFERENCES `mydb`.`Utente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posto` (
  `idPosto` INT NOT NULL,
  `fila` INT NOT NULL,
  `lettera` INT NOT NULL,
  `prenotazione` INT NULL,
  `volo` VARCHAR(8) NOT NULL,
  INDEX `prenotazione_idx` (`prenotazione` ASC) VISIBLE,
  PRIMARY KEY (`idPosto`),
  INDEX `codice_volo_idx` (`volo` ASC) VISIBLE,
  CONSTRAINT `voloPosto`
    FOREIGN KEY (`volo`)
    REFERENCES `mydb`.`Volo` (`codice_volo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `prenotazionePosto`
    FOREIGN KEY (`prenotazione`)
    REFERENCES `mydb`.`Prenotazione` (`codicePrenotazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biglietto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biglietto` (
  `idBiglietto` INT NOT NULL,
  `NomePasseggero` VARCHAR(45) NOT NULL,
  `CognomePasseggero` VARCHAR(45) NOT NULL,
  `DataNascita` DATE NOT NULL,
  `prenotazione` INT NOT NULL,
  `utente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBiglietto`),
  INDEX `prenotazione_idx` (`prenotazione` ASC) VISIBLE,
  INDEX `utente_idx` (`utente` ASC) VISIBLE,
  CONSTRAINT `prenotazioneBiglietto`
    FOREIGN KEY (`prenotazione`)
    REFERENCES `mydb`.`Prenotazione` (`codicePrenotazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utenteBiglietto`
    FOREIGN KEY (`utente`)
    REFERENCES `mydb`.`Utente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartaFedeltà`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CartaFedeltà` (
  `idCartaFedeltà` INT NOT NULL,
  `puntiTessera` INT NOT NULL DEFAULT 0,
  `utente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCartaFedeltà`),
  INDEX `utente_idx` (`utente` ASC) VISIBLE,
  CONSTRAINT `utenteCartaFedeltà`
    FOREIGN KEY (`utente`)
    REFERENCES `mydb`.`Utente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promozione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promozione` (
  `idPromozione` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `scontoPerFedeli` DECIMAL(2) NULL,
  `scontoPerTutti` DECIMAL(2) NULL,
  `perTutti` TINYINT NULL DEFAULT 0,
  `dataInizio` DATE NULL,
  `dataFine` DATE NULL,
  PRIMARY KEY (`idPromozione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `importo` DECIMAL(2) NOT NULL,
  `cartaFedeltà` INT NULL,
  `prenotazione` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `cartaFedeltà_idx` (`cartaFedeltà` ASC) VISIBLE,
  INDEX `prenotazione_idx` (`prenotazione` ASC) VISIBLE,
  CONSTRAINT `cartaFedeltàPagamento`
    FOREIGN KEY (`cartaFedeltà`)
    REFERENCES `mydb`.`CartaFedeltà` (`idCartaFedeltà`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prenotazionePagamento`
    FOREIGN KEY (`prenotazione`)
    REFERENCES `mydb`.`Prenotazione` (`codicePrenotazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

